//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Leaderboards.Authoring.Client.Http;



namespace Unity.Services.Leaderboards.Authoring.Client.Models
{
    /// <summary>
    /// LeaderboardVersionRange model
    /// </summary>
    [Preserve]
    [DataContract(Name = "LeaderboardVersionRange")]
    internal class LeaderboardVersionRange
    {
        /// <summary>
        /// Creates an instance of LeaderboardVersionRange.
        /// </summary>
        /// <param name="version">version param</param>
        /// <param name="results">results param</param>
        [Preserve]
        public LeaderboardVersionRange(LeaderboardVersion2 version = default, List<LeaderboardEntry2> results = default)
        {
            Version = version;
            Results = results;
        }

        /// <summary>
        /// Parameter version of LeaderboardVersionRange
        /// </summary>
        [Preserve]
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public LeaderboardVersion2 Version{ get; }
        
        /// <summary>
        /// Parameter results of LeaderboardVersionRange
        /// </summary>
        [Preserve]
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<LeaderboardEntry2> Results{ get; }
    
        /// <summary>
        /// Formats a LeaderboardVersionRange into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Version != null)
            {
                serializedModel += "version," + Version.ToString() + ",";
            }
            if (Results != null)
            {
                serializedModel += "results," + Results.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a LeaderboardVersionRange as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
