//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Leaderboards.Authoring.Client.Http;



namespace Unity.Services.Leaderboards.Authoring.Client.Models
{
    /// <summary>
    /// LeaderboardIdConfig1AllOf model
    /// </summary>
    [Preserve]
    [DataContract(Name = "LeaderboardIdConfig_1_allOf")]
    internal class LeaderboardIdConfig1AllOf
    {
        /// <summary>
        /// Creates an instance of LeaderboardIdConfig1AllOf.
        /// </summary>
        /// <param name="id">id param</param>
        /// <param name="bucketSize">bucketSize param</param>
        [Preserve]
        public LeaderboardIdConfig1AllOf(string id, int bucketSize = default)
        {
            Id = id;
            BucketSize = bucketSize;
        }

        /// <summary>
        /// Parameter id of LeaderboardIdConfig1AllOf
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id{ get; }
        
        /// <summary>
        /// Parameter bucketSize of LeaderboardIdConfig1AllOf
        /// </summary>
        [Preserve]
        [DataMember(Name = "bucketSize", EmitDefaultValue = false)]
        public int BucketSize{ get; }
    
        /// <summary>
        /// Formats a LeaderboardIdConfig1AllOf into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Id != null)
            {
                serializedModel += "id," + Id + ",";
            }
            serializedModel += "bucketSize," + BucketSize.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a LeaderboardIdConfig1AllOf as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Id != null)
            {
                var idStringValue = Id.ToString();
                dictionary.Add("id", idStringValue);
            }
            
            var bucketSizeStringValue = BucketSize.ToString();
            dictionary.Add("bucketSize", bucketSizeStringValue);
            
            return dictionary;
        }
    }
}
