//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Leaderboards.Authoring.Client.Http;



namespace Unity.Services.Leaderboards.Authoring.Client.Models
{
    /// <summary>
    /// PageInfo model
    /// </summary>
    [Preserve]
    [DataContract(Name = "PageInfo")]
    internal class PageInfo
    {
        /// <summary>
        /// Creates an instance of PageInfo.
        /// </summary>
        /// <param name="endCursor">endCursor param</param>
        [Preserve]
        public PageInfo(string endCursor = default)
        {
            EndCursor = endCursor;
        }

        /// <summary>
        /// Parameter endCursor of PageInfo
        /// </summary>
        [Preserve]
        [DataMember(Name = "endCursor", EmitDefaultValue = false)]
        public string EndCursor{ get; }
    
        /// <summary>
        /// Formats a PageInfo into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (EndCursor != null)
            {
                serializedModel += "endCursor," + EndCursor;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a PageInfo as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (EndCursor != null)
            {
                var endCursorStringValue = EndCursor.ToString();
                dictionary.Add("endCursor", endCursorStringValue);
            }
            
            return dictionary;
        }
    }
}
