//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Leaderboards.Authoring.Client.Http;

//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


namespace Unity.Services.Leaderboards.Authoring.Client.Models
{
    /// <summary>
    /// UpdateType enum.
    /// </summary>
    /// <value>The Update Type of the Leaderboard, currently limited to Keep Best Score (keepBest), Keep Latest Score (keepLatest), Keep Total Score (aggregate)</value>
    
    [Preserve]
    [JsonConverter(typeof(StringEnumConverter))]
    internal enum UpdateType
    {
        /// <summary>
        /// Enum KeepBest for value: keepBest
        /// </summary>
        [EnumMember(Value = "keepBest")]
        KeepBest = 1,

        /// <summary>
        /// Enum KeepLatest for value: keepLatest
        /// </summary>
        [EnumMember(Value = "keepLatest")]
        KeepLatest = 2,

        /// <summary>
        /// Enum Aggregate for value: aggregate
        /// </summary>
        [EnumMember(Value = "aggregate")]
        Aggregate = 3

    }
}



